apiVersion: v1
kind: Service
metadata:
  name: {{ include "sine-service.fullname" . }}
  labels:
    app: {{ include "sine-service.name" . }}
    chart: {{ include "sine-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ include "sine-service.fullname" . }}
      protocol: TCP
      name: {{ include "sine-service.fullname" . }}
  selector:
    app: {{ include "sine-service.name" . }}
    release: {{ .Release.Name }}
