config_docker: &config_docker
  docker:
    - image: jspc/ci-worker:1.4.0
  resource_class: small

version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    <<: *config_docker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -tests
      - run:
          name: Test
          command: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: coverage.txt

  deploy:
    <<: *config_docker
    steps:
    - checkout
    - run: git submodule update --init
    - setup_remote_docker:
        docker_layer_caching: true
    - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    - run: CGO_ENABLED=0 go build
    - run: make docker
    - run: make publish
    - run: make helm-repo-add
    - run: make helm-repo-update
    - run: make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          context: BUILD
          filters:
            tags:
              only: /.*/
      - deploy:
          context: BUILD
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
